### PR TITLE
Tech ydiago

### PR DESCRIPTION
**Pull request by sangallidavide**
Small fix to issue noticed by @muralidhar-nalabothula (compilation of scalapack always enabled)

### CODE REVIEW

**Comment by muralidhar-nalabothula** [comment]
Hi Davide, 

It still tries to compile internal scalapack library.

More importantly, The preprocessor flag ```-D_ELPA``` is not used when creating ```.f90``` from ```.F``` files. Although it says ELPA Diagonalization (which is not guarded by ifdef), it is always running scalapack diagonalization (this is the reason why you see same timing for elpa and scalapack)

**Comment by sangallidavide** [comment]
> It still tries to compile internal scalapack library.

Yeap, sorry, I messed up with merging the branches and I did not re-run autoconf last time.

> More importantly, The preprocessor flag -D_ELPA is not used when creating .f90 from .F files. 

Ok, fixing this as well

**Comment by sangallidavide** [comment]
Now it should be ok.

**Comment by muralidhar-nalabothula** [comment]
All issues fixed. For me this PR can be merged. If you get some time, you can also test GPU version (v.0.3.0 also supports GPU: CUDA, HIP, INTEL, simply compile ELPA and yambo for GPUs .).  I think, for now, that's all from my side. Let me know if you have any issues when testing.

**Comment by sangallidavide** [comment]
Yeap, GPU testing is also on the todo list with slepc. When I'll work on it, I'll aso try ydiago+elpa with CUDA and update the report on BSE solvers.

**Pull request merged**
