### PR TITLE
New Ydiago interface 

### PR DESCRIPTION
**Pull request by muralidhar-nalabothula**
Dear All,

A preliminary interface with the new diagonalization solver Ydiago (https://github.com/yambo-code/Ydiago) has been implemented. ~~Currently, I manually link the library (libdiago.a) after the configure step is done (@sangallidavide agreed to link it in Sept/Oct).~~ Please refer to issue https://github.com/yambo-code/yambo/issues/113 for more details.

Motivation:

To speed up BSE diagonalization
To port it to modern hardware
To make the code more modular. Currently, porting any new solver brings a lot of clutter, code duplication, etc. Here we separate out the diagonalization routines into a library and call the library. In this way, we need minimal changes in the main YAMBO code when adding new features.
Here is what is implemented:

1) Parallel solvers for TDA and non-TDA when l_BS_ares_from_res = .true. using SCALAPACK (SL) and ELPA. These two cases will be GPU ported very soon using ELPA. Note that the code can take additional low-level optimizations which can give a massive speedup for non-TDA calculations.

2) To deal with the diagonalization of very general non-Hermitian matrices, a completely new parallel solver is built using the bare bones of SCALAPACK functions. (This is not GPU ported, as SL is CPU-only code as of today.)

3) Parallel distribution of eigenvectors. The code now distributes computed eigenvectors among all CPUs (earlier, every CPU got the full set of eigenvectors, which led to blowing up in memory).

4) Due to point 3, I had to rewrite the residual computation routines to account for the new eigenvector distribution support. PL residuals are not implemented as it is broken; see https://github.com/yambo-code/yambo/issues/116. ~~I also did not implement BS_perturbative corrections (both for SOC and lifetimes)~~.

5) Parallel I/O is adopted to write the eigenvectors (additional optimizations such as chunking are also implemented).

TODO:

1) If PL is fixed, I will try to implement it, ~~and BS_perturbative corrections will be coded later~~.

2) Code cleanup (need help). I almost did not change the existing code, which led to duplication of code for residual functions. I will leave this to senior developers to organize. I also assume that the user compiles the code with MPI library and SCALAPACK, so these things should be taken care of.

3) More extensive testing. I did preliminary tests which look fine to me. I am not able to run the test suite on my machine. If someone can test it, that would be great.

4) I currently disabled the GPU support (in Ydiago library) as I donot have a machine to test it. This will be very soon made available.

I opened this PR with the intention that senior devs can have a look at the code and make suggestions, comments, and edits. Please note that this is my first time writing serious Fortran code; some things may look stupid or may not be valid Fortran code, so sorry for that. I would like to leave this PR open for a longer time, as it is easily to review small changes. I will update things slowly from now on.

Thank you,

Best regards,
Murali

### CODE REVIEW

**Comment by sangallidavide** [comment]
Thanks Murali.

1. The PL is broken, and we do not need to fix it with the present PR
3. Ok, cleaning can come later
4. Ok, I can test it. I think I'll create a tech-ydiago from your branch inside the gpl repo
5. Ok, gpu support can come later

**Comment by muralidhar-nalabothula** [comment]
Thanks Davide, As you said to before, there are cases where l_BS_ares_from_res is false, Could you please point me to that case, as I want this case test.

**Comment by sangallidavide** [comment]
>     3. Ok, I can test it. I think I'll create a tech-ydiago from your branch inside the gpl repo

I'm trying to compile the code linking libdiago.a
However I get the following errors. Any suggestion?
```
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(bse_solver.o): in function `BSE_Solver':
bse_solver.c:(.text+0x194): undefined reference to `pspotrf_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(geev.o): in function `Geev':
geev.c:(.text+0x1ca): undefined reference to `pcgehrd_'
/usr/bin/ld: geev.c:(.text+0x2a8): undefined reference to `pcgehrd_'
/usr/bin/ld: geev.c:(.text+0x388): undefined reference to `pcunmhr_'
/usr/bin/ld: geev.c:(.text+0x438): undefined reference to `pcunmhr_'
/usr/bin/ld: geev.c:(.text+0x5bd): undefined reference to `pclahqr_'
/usr/bin/ld: geev.c:(.text+0x6bc): undefined reference to `pclahqr_'
/usr/bin/ld: geev.c:(.text+0x860): undefined reference to `pctrevc_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(heev.o): in function `Heev':
heev.c:(.text+0x33b): undefined reference to `pcheevr_'
/usr/bin/ld: heev.c:(.text+0x4f1): undefined reference to `pcheevr_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(backtransform_bse_QLZ.o): in function `BtEig_QLZ':
backtransform_bse_QLZ.c:(.text+0x33e): undefined reference to `pstrmr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x409): undefined reference to `pstrmr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x47d): undefined reference to `pstrmr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x4ed): undefined reference to `pstrmr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x55c): undefined reference to `psgemr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x5c0): undefined reference to `psgemr2d_'
/usr/bin/ld: backtransform_bse_QLZ.c:(.text+0x6aa): undefined reference to `pstrmr2d_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(bse_skew_symmetric.o): in function `Omega_times_L.part.0':
bse_skew_symmetric.c:(.text+0x124): undefined reference to `psgemr2d_'
/usr/bin/ld: bse_skew_symmetric.c:(.text+0x184): undefined reference to `pstrmr2d_'
/usr/bin/ld: bse_skew_symmetric.c:(.text+0x225): undefined reference to `pstrmr2d_'
/usr/bin/ld: bse_skew_symmetric.c:(.text+0x29a): undefined reference to `pstrmr2d_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(bse_skew_symmetric.o): in function `Construct_bseW':
bse_skew_symmetric.c:(.text+0x40b): undefined reference to `pstrmm_'
/usr/bin/ld: /data/shared/yambo-libs/default//gfortran/mpifort.openmpi/lib/libydiago.a(build_bseHamR.o): in function `Construct_BSE_RealHam':
build_bseHamR.c:(.text+0x1d2): undefined reference to `psgemr2d_'
/usr/bin/ld: build_bseHamR.c:(.text+0x230): undefined reference to `psgemr2d_'
/usr/bin/ld: build_bseHamR.c:(.text+0x294): undefined reference to `psgemr2d_'

```

**Comment by sangallidavide** [comment]
> Thanks @sangallidavide , As you said to before, there are cases where l_BS_ares_from_res is false, Could you please point me to that test case, as I want this test it my self.

See the flag `l_BS_ares_from_res` inside `K_driver_init`, these 3 cases (well 2, since PL can be ignored for now)
```
 if (iq/=1.and.i_time_rev==0.and.i_space_inv==0 )  l_BS_ares_from_res=.FALSE.
 if (l_BS_photolum)                                l_BS_ares_from_res=.FALSE.
 if (l_BS_magnons.and.n_sp_pol==2)                 l_BS_ares_from_res=.FALSE.
```
The easiest case is probably magnons with n_sp_pol=2. There is Iron in the test-suite.
https://github.com/yambo-code/yambo-tests/tree/master/TESTS/MAIN/Iron/pwscf/Without-SOC
You can try the 04_MAGNONS_ALDA input file

**Comment by muralidhar-nalabothula** [comment]
> I'm trying to compile the code linking libdiago.a
> However I get the following errors. Any suggestion?

1) you forget to give the include path for ydiago_interface.mod, that you will find in the src after compiling.
2) Scalapack is must as the library internally calls scalapack functions
3) If you are already linking scalapack and are seeing this error, this implies that you are not linking the libraries in correct order. As libdiago is static lib and calls SL function, you need to link the libscalapack.a after libdiago.a ie. 
-ldiago -lscalapack -llapack -lblas. 

In case you wish to compile with elpa, the link order is as follows -ldiago -lelpa -lscalapack -llapack -lblas. 

I am not sure if this the order used when linking https://github.com/muralidhar-nalabothula/yambo/blob/master/sbin/compilation/libraries.sh#L20, if so,
it should ```lPLA="\$(lydiago) \$(lscalapack) \$(lblacs) \$(llapack) \$(lblas) "```.
in case of elpa ```lPLA="\$(lydiago) \$(lelpa) \$(lscalapack) \$(lblacs) \$(llapack) \$(lblas) "```

**Comment by sangallidavide** [comment]
Indeed, I forgot the module. Thanks, now it works.

**Comment by sangallidavide** [comment]
Ok, I had a  look to the coding. 

2 things for now.

a) the spaces are completely changed inside the subroutine K_diago_driver. As a consequence, if I do git diff it shows that the subroutine is completely changed. Do you mind if I restore the older spacing for now?
This will also help later merging with tech-master.

b) I see l_diago is off by defult, and l_yadiago is on. I'd change like that
```
l_ydiago    = index(BSS_mode,'d')/=0
l_diago      = index(BSS_mode,'o')/=0 ! o for "old diago"
```
Old diago can be removed in the future

@murali : If you give me ok, I'll create a pull request with space changes in K_diago_driver.

**Comment by muralidhar-nalabothula** [comment]
Ofcourse, please feel free to do whatever changes you want. 
There is one more place which requires your intervention. In https://github.com/muralidhar-nalabothula/yambo/blob/master/src/io/io_BSS_diago.F#L227%20and%20https://github.com/muralidhar-nalabothula/yambo/blob/master/src/io/io_BSS_diago.F#L236
I used some random values for VAR_ID, I am not sure what exactly are these and how to set them. For now, I set them to large temporary values. Could you also have a look and fix this if there you see a problem?

**Comment by sangallidavide** [comment]
Ok, it was just to check that you were not changing the file right now. Pull request created.

I did few tests on a small matrix (2688x2688)

Old yambo diagonalization
```
- serial: 1m12s
- 4 mpi: 1m34s (Blacs 2x2)
```
New Ydigao
```
- serial: 40 s
- 4 mpi: 15 s (Blacs 2x2)
```

**Comment by sangallidavide** [comment]
Ok, if you accept the last pull request the code will be up to date with the tech-master.

I've seen the coding. The part of the residuals needs to be better integrated with the existing code and also the I/O. I'll think about how to do that. Also I might like to slightly change the structure of K_diago_driver. But these things in the future. For now I'll keep on testing the code.

About the `VAR_ID`, random numbers are fine. Usually I just use progressive numbers. The only requirement is that every variable inside a given file has a different number.

**Comment by muralidhar-nalabothula** [comment]
>I've seen the coding. The part of the residuals needs to be better integrated with the existing code and also the I/O. I'll think about how to do that. Also I might like to slightly change the structure of K_diago_driver. But these things in the future. For now I'll keep on testing the code.

Agree ```K_diago_driver.F``` needs some cleanup. There are additional options that I did not use in ```K_diagonalize``` subroutine (for example, selecting the solver, eigenvalues value range, eigenvalue index range etc). We need to add input variables and make them available to the user.


> Ok, it was just to check that you were not changing the file right now. Pull request created.
> 
> I did few tests on a small matrix (2688x2688)
> 
> Old yambo diagonalization
> 
> ```
> - serial: 1m12s
> - 4 mpi: 1m34s (Blacs 2x2)
> ```
> 
> New Ydigao
> 
> ```
> - serial: 40 s
> - 4 mpi: 15 s (Blacs 2x2)
> ```

I went to a bit extreme. Ran a massive diagonalization test (```147456 x 147456``` using ```32 nodes``` with each node containing ```28 cpus and 64 Gb of Ram```). Paralleization scheme ``` 128 MPI```, ```7 Threads```
Here are the results. Used Intel fortran compiler, MKL libraries. Peak memory touched : ```~1.3 Tb```. BSE kernel and Eigen vector file size : ```~163 Gb```.
```
 <33s> P1-iris-001: [BSK] Size (resonant):  147456
 <33s> P1-iris-001: [BSK]         (total):  147456
 <33s> P1-iris-001: [BSK] N. of matrices :  1

<02h-02m> P1-iris-001: [WARNING] Allocation attempt of BS_E of zero size.
 <02h-02m> P1-iris-001: [WARNING] Allocation attempt of BS_R_left of zero size.
 <02h-02m> P1-iris-001: [WARNING] Allocation attempt of BS_R_right of zero size.
 <02h-02m> P1-iris-001: Folding BSE Kernel |                                        | [000%] --(E) --(X)
 <02h-02m> P1-iris-001: Folding BSE Kernel |########################################| [100%] --(E) --(X)
 <02h-02m> P1-iris-001: BLACS grid:  11  11
 <02h-02m> P1-iris-001: Filling BSE Matrix |                                        | [000%] --(E) --(X)
 <02h-04m> P1-iris-001: Filling BSE Matrix |########################################| [100%] 02m-21s(E) 02m-21s(X)
 <02h-04m> P1-iris-001: [10.01.08] Scalapack Diagonalization
 <02h-04m> P1-iris-001: BSK diagonalize |                                        | [000%] --(E) --(X)
 <03h-14m> P1-iris-001: BSK diagonalize |########################################| [100%] 01h-09m(E) 01h-09m(X)
 <03h-14m> P1-iris-001: Folding Right eigenvectors |                                        | [000%] --(E) --(X)
 <03h-16m> P1-iris-001: Folding Right eigenvectors |########################################| [100%] 01m-52s(E) 01m-52s(X)
 <03h-16m> P1-iris-001: EPS R residuals |                                        | [000%] --(E) --(X)
 <03h-16m> P1-iris-001: EPS R residuals |########################################| [100%] --(E) --(X)
 <03h-16m> P1-iris-001: BSK resp. funct |                                        | [000%] --(E) --(X)
 <03h-16m> P1-iris-001: BSK resp. funct |########################################| [100%] --(E) --(X)

==========================================================================================

 <03h-17m> P1-iris-001: [TIMING]                io_BSS_diago :     53.4985s CPU (    3 calls,  17.833 sec avg)
 <03h-17m> P1-iris-001: [TIMING]                       io_BS :      36m-52s CPU (48636 calls,   0.045 sec avg)
 <03h-17m> P1-iris-001: [TIMING]           T_space CORR Osc. :      53m-02s CPU (48636 calls,   0.065 sec avg)
 <03h-17m> P1-iris-001: [TIMING]               Ydiago Solver :      01h-15m CPU
 <03h-17m> P1-iris-001: [TIMING]            X T_space Kernel :      02h-01m CPU
```

I also see a massive speedup in eigenvectors IO, hitting nearly ``` 3GB/sec``` (lustre with 16 OSTs).
Please note that we can speedup ```Filling BSE Matrix``` and ```Folding Right eigenvectors``` a bit more by using openmp. Currently they are single threaded, so they do not scale with threads.

**Comment by muralidhar-nalabothula** [comment]
Most of the testcases passes(The failed cases also failed with tech-bse branch, so I assume they are not related to this changes) Here is the report of test 
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Yambo test suite global REPORT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Yambo      branch       :any
Test-suite branch       :master
==================================================================================
Running tests           :all
Projects                : magnetic nopj kerr
Date - Time             :Aug-4-Sun - 14-26
Build                   :any - MPI+OpenMP+SLK+HDF5_MPI_IO - OpenMPI - gfortran - rev.23122
Repo Kind               :GPL
Fortran                 :gfortran  GNU Fortran (GCC) 10.2.0
MPI                     : Open MPI v4.0.5, package: Open MPI resif@iris-001 Distribution, ident: 4.0.5, repo rev: v4.0.5, Aug 26, 2020
Compilation Precision   :single
Parallel Conf           :[(N=8)(Threads=1)] - single, default parallelization
=--------------------------------------------------------------------------------=
 >  [  1/ 74] Al111[(N=8)(Threads=1)]                                      3 passes                 6.60 [  2.20/test]
 >  [  3/ 74] Al_bulk/GW-OPTICS[(N=8)(Threads=1)]                          5 passes                14.00 [  2.80/test]
 >  [  6/ 74] Benzene/GW-OPTICS[(N=8)(Threads=1)]                         15 passes                49.00 [  3.27/test]
 >  [  7/ 74] Benzene/MAGNETIC[(N=8)(Threads=1)]                          17 passes                76.50 [  4.50/test]
 >  [  8/ 74] Beryllium/YPP[(N=8)(Threads=1)]                              6 passes                72.60 [ 12.10/test]
 >  [ 11/ 74] C6H3Cl3[(N=8)(Threads=1)]                                    8 passes                33.00 [  4.13/test]
 >  [ 12/ 74] CH4/Distorted_A[(N=8)(Threads=1)]                            3 passes     1 fails    19.70 [  4.93/test]
 >  [ 13/ 74] CH4/Distorted_B[(N=8)(Threads=1)]                            3 passes     1 fails    19.70 [  4.93/test]
 >  [ 14/ 74] CH4/MAGNETIC[(N=8)(Threads=1)]                               5 passes     1 fails    21.60 [  3.60/test]
 >  [ 15/ 74] CH4/Symmetric[(N=8)(Threads=1)]                              0 passes     3 fails    14.90 [  4.97/test]
 >  [ 16/ 74] CH4/Symmetric_b3lyp[(N=8)(Threads=1)]                        2 passes     1 fails    14.00 [  4.67/test]
 >  [ 20/ 74] H2/OPTICS[(N=8)(Threads=1)]                                  9 passes                20.90 [  2.33/test]
 >  [ 23/ 74] H_chain/2.05[(N=8)(Threads=1)]                               4 passes                20.60 [  5.15/test]
 >  [ 24/ 74] H_chain/2.5[(N=8)(Threads=1)]                                4 passes                21.40 [  5.35/test]
 >  [ 25/ 74] hBN/GW-ANISOTROPY[(N=8)(Threads=1)]                          6 passes                22.90 [  3.82/test]
 >  [ 26/ 74] hBN/GW-OPTICS[(N=8)(Threads=1)]                             44 passes               164.40 [  3.74/test]
 >  [ 27/ 74] hBN/GW-SHIFTED/REGULAR[(N=8)(Threads=1)]                     1 passes                 4.20 [  4.20/test]
 >  [ 28/ 74] hBN/GW-SHIFTED/SHIFTED[(N=8)(Threads=1)]                     1 passes                 3.50 [  3.50/test]
 >  [ 30/ 74] hBN/NONDIAGCELL[(N=8)(Threads=1)]                            1 passes                 3.20 [  3.20/test]
 >  [ 35/ 74] hBN/YPP[(N=8)(Threads=1)]                                    5 passes                 6.80 [  1.36/test]
 >  [ 36/ 74] He/GW[(N=8)(Threads=1)]                                      0 passes                 1.40 [  0.00/test]
 >  [ 38/ 74] Iron/abinit/Without-SOC[(N=8)(Threads=1)]                    8 passes                19.60 [  2.46/test]
 >  [ 39/ 74] Iron/abinit/With-SOC[(N=8)(Threads=1)]                       4 passes                 7.90 [  1.98/test]
 >  [ 40/ 74] Iron/pwscf/Without-SOC[(N=8)(Threads=1)]                    11 passes                60.90 [  5.54/test]
 >  [ 41/ 74] Iron/pwscf/With-SOC[(N=8)(Threads=1)]                       16 passes                51.20 [  3.20/test]
 >  [ 43/ 74] LiF/GW-OPTICS[(N=8)(Threads=1)]                             20 passes                57.60 [  2.88/test]
 >  [ 47/ 74] MoS2/abinit/OPTICS/Without-SOC-sp1[(N=8)(Threads=1)]        17 passes                45.60 [  2.69/test]
 >  [ 48/ 74] MoS2/abinit/OPTICS/Without-SOC-sp2[(N=8)(Threads=1)]         4 passes                10.60 [  2.65/test]
 >  [ 49/ 74] MoS2/abinit/OPTICS/With-SOC[(N=8)(Threads=1)]               15 passes                75.20 [  5.02/test]
 >  [ 50/ 74] MoS2/abinit/OPTICS/WithScreen-SOC[(N=8)(Threads=1)]          1 passes                21.80 [ 21.80/test]
 >  [ 54/ 74] MoS2/pwscf/OPTICS/Without-SOC-sp1[(N=8)(Threads=1)]         12 passes                54.00 [  4.50/test]
 >  [ 55/ 74] MoS2/pwscf/OPTICS/Without-SOC-sp2[(N=8)(Threads=1)]          5 passes                16.20 [  3.24/test]
 >  [ 56/ 74] MoS2/pwscf/OPTICS/With-SOC[(N=8)(Threads=1)]                 6 passes                36.30 [  6.05/test]
 >  [ 58/ 74] NiBr2/Without-SOC/GW-OPTICS[(N=8)(Threads=1)]                2 passes                 7.10 [  3.55/test]
 >  [ 59/ 74] PA_chain[(N=8)(Threads=1)]                                  10 passes                33.80 [  3.38/test]
 >  [ 66/ 74] Si_bulk/GW-OPTICS[(N=8)(Threads=1)]                         34 passes               141.60 [  4.17/test]
 >  [ 67/ 74] Si_bulk/PBE0[(N=8)(Threads=1)]                               1 passes                 2.00 [  2.00/test]
 >  [ 71/ 74] Si_surface/OPTICS[(N=8)(Threads=1)]                          8 passes                21.90 [  2.74/test]
 >  [ 72/ 74] Si_wire/OPTICS[(N=8)(Threads=1)]                            11 passes                19.90 [  1.81/test]

Tests: 7 FAIL, 341 OK, 149 SKIPS( 44 SETUP, 8 CPU-CONF)
Test FAIL detail: 7 WRONG, 0 NO RUN 0 RUNTIME
=--------------------------------------------------------------------------------=
Checks: 7 FAIL, 1237 OK, 3 WHITELIST 0 RULES-SUCC
Check FAIL detail: 7 WRONG, 0 no REF, 0 no OUT, 0 no DB
=--------------------------------------------------------------------------------=
% Section Duration : 0:21:37 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% TOTAL   Duration : 0:21:37 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

Failed cases
```
TESTS/MAIN/CH4/Distorted_A/ROBOT_Nr_1/01_IP_dichroism-Nmpi8-def_par-any
TESTS/MAIN/CH4/Distorted_B/ROBOT_Nr_1/01_IP_dichroism-Nmpi8-def_par-any
TESTS/MAIN/CH4/MAGNETIC/ROBOT_Nr_1/04_bse-Nmpi8-def_par-any
TESTS/MAIN/CH4/Symmetric/ROBOT_Nr_1/01_IP_dichroism-Nmpi8-def_par-any
TESTS/MAIN/CH4/Symmetric/ROBOT_Nr_1/02_BSE-Nmpi8-def_par-any
TESTS/MAIN/CH4/Symmetric/ROBOT_Nr_1/02_BSE_CPL-Nmpi8-def_par-any
TESTS/MAIN/CH4/Symmetric_b3lyp/ROBOT_Nr_1/01_IP_dichroism-Nmpi8-def_par-any
```

**Comment by sangallidavide** [comment]
Hi Murali, thanks. Just a comment.

At present, when redistributing from the yambo way (`BS_blks`) to the explicit slepc way (`slepc_mat`), the whole BSE kernel is kept in memory twice. This is a factor 2 in memory. I recently change this in branch tech-isolv-bse. The code is reading the BS_blks directly from disk without keeping them in memory (if the file on disk is available). See this file:
https://github.com/yambo-code/yambo/blob/tech-isolv-bse/src/bse/K_stored_in_a_slepc_matrix.F

Code highlighted here.
```
 do i_B=1,n_BS_blks
   !
   ...
   !
   if (BSS_kernel_IO_on_the_fly) then
     call io_control(ACTION=RD,ID=BS_ID(2))
     call io_BS_PAR_block(iq,i_B,BS_ID(2),"matonly")
   endif
   !
   ...
   !
   if (BSS_kernel_IO_on_the_fly) call K_block_free(i_B)
   !
   ...
   !
enddo
```

For now, nothing to do on your side. In the future, I'd say we can insert this logic also in your
https://github.com/muralidhar-nalabothula/yambo/blob/master/src/bse/K_fill_block_cyclic.F

Side consideration. Following the yambo logic, the call to K_fill_block_cyclic could be moved inside the new K_diago_driver. 
Not sure if the yambo logic is the best one, maybe we should discuss what is the most logic structure ...
Something like

```
 if (l_diago) then
   ...
   call K_stored in a big_matrix
   ...
endif
!
if (l_ydiago) then
   ...
   call K_fill_block_cyclic
  ...
endif
```

**Comment by muralidhar-nalabothula** [comment]
Hi Davide,

The peak memory foot print is roughly 6 times the size of bse kernel when using ydiago solver. I added the free blocks, that will free some space, but the optimization you are doing won't affect the peak memory foot print when using ydiago solver. But the good thing it will memory does not scale with number cores, indicating that the user simply runs the calculation with more cores if the memory is insufficient.

**Comment by sangallidavide** [comment]
I'm testing the code on a local cluster.

On a matrix of size ~ `10^4x10^4` it works fine. When I move to a matrix of size ~`3*10^4x3*10^4` it fails. Both with 16, 64, and 90 MPI tasks.

This is the error message is the same in all cases (below on 16 MPI tasks)
```
{    0,    0}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    0,    1}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    0,    2}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    0,    3}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    1,    0}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    1,    1}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    1,    2}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    1,    3}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    2,    0}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    2,    1}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    2,    2}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    2,    3}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    3,    0}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    3,    1}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    3,    2}:  On entry to PCHEEVR parameter number   23 had an illegal value
{    3,    3}:  On entry to PCHEEVR parameter number   23 had an illegal value
--------------------------------------------------------------------------
```
If I'm not wrong parameter 23 is lrwork, and printing it I get 
On 16 MPI tasks: `lrwork value is 165155136`
On 90 MPI tasks: `lrwork value is 59254400`

**Comment by muralidhar-nalabothula** [comment]
Hi Davide,

Looking at these:
> If I'm not wrong parameter 23 is lrwork, and printing it I get On 16 MPI tasks: `lrwork value is 165155136` On 90 MPI tasks: `lrwork value is 59254400`

You are victim of ```float``` to ```int``` precision error. It it not a bug in the Ydiago code, but rather a poor design choice of scalapack routine. If you look at https://github.com/Reference-ScaLAPACK/scalapack/blob/master/SRC/pcheevr.f#L592
the code converts an ```int`` to ```float```. Given that ```165155136``` is stored as ```1.65155136 1e8``` and we know float can store 6-7 decimals,  you will round off to a number less or more than the original integer. Unfortunaly, in this case, it is less, so you see this error. One can fix this by increasing the number by  ```0.1%``` more. I will fix in the library soon.

**Comment by sangallidavide** [comment]
Yeah, I guessed it was something like that. Thanks Murali.
Isn't a bit stupid that scalapack uses a single precision real to return an integer number? 

I also guess that, in the present version, the error goes away if one increases enough the number of MPI tasks. This is why you did not experience it on a larger matrix, right?

I understand you can fix this by increasing the number of 0.1% because a larger value is admitted, right? We probably just waste a bit of memory, right?

A maybe safer approach could be to put a check on the value. Only if the number is larger that some maximum / checking internally a integer --> real --> integer conversion, the subroutine applies the 0.1% increase (with a warning message suggesting to increase the number of MPI tasks?)

**Comment by muralidhar-nalabothula** [comment]
@sangallidavide  I introduced a workaround in the latest commit. Let me know if you still see this error.

I choose the values to be ```0.01 %```. This should be enough as float can store values < 10K without loss of precision. The memory increase is negligible (will increase memory by ```1 MB``` if the original is ```10 GB```). so we do not really need to bother about memory increase at all.

> Isn't a bit stupid that scalapack uses a single precision real to return an integer number?
I think they wrote these routines for double precision and simply changed the prefix for SP. You never encounter this issue with ```double``` as it can perfectly store any ```32 bit``` integer. It would have nicer if they changed the lwork directly when query request is made instead of int->float->int conversion.

>I also guess that, in the present version, the error goes away if one increases enough the number of MPI tasks. This is why you did not experience it on a larger matrix, right?

Yes, When increase the mpi tasks, we decrease the value which is perfectly fine to be stored in float.

**Comment by sangallidavide** [comment]
Thanks. With the workaround it works. I'll report this to the Scalapack developers.
Let's see how they react.

**Comment by sangallidavide** [comment]
Addendum.

On the `3*40^4` matrix, the resonant case works just fine.
The coupling case fails, e.g. the code crashes, for some CPU configurations.
Specifically:
- 2 nodes x 18 cores= 36 cores (6x6 blacs grid) [OK]
- 2 nodes x 32 cores= 64 cores (8x8 blacs grid) [OK]
- 2 nodes x 25 cores= 50 cores (7x7 blacs grid) [FAIL]
- 2 nodes x 28 cores= 56 cores (7x8 blacs grid) [FAIL]

Interrupted log:
```
 <44s> P1-wnode09: Filling BSE Matrix |                                        | [000%] --(E) --(X)
 <02m-40s> P1-wnode09: Filling BSE Matrix |########################################| [100%] 01m-55s(E) 01m-55s(X)
 <02m-41s> P1-wnode09: [05.04] Scalapack Diagonalization
```
Slurm fail message:
```
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 13(/22) with PID 0 on node wnode09 exited on signal 9 (Killed).
--------------------------------------------------------------------------
```

**Comment by muralidhar-nalabothula** [comment]
is the total matrix size ```30K``` or ```70K``` ? Do you see any other error message (other than slurmn)?

Ydiago code never Aborts (unless scalapack calls it. If Scalapack calls the exit, it with output an error message on slurmn output)
If scalapack is not calling the Abort function, then it should be Yambo that is killing the program (yambo should print an message incase of an error).

If you do not see any error message, very likely, memory allocation was failed in yambo code (in K_diagonalize.F file). Maybe you can try increasing the memory per core?

**Comment by sangallidavide** [comment]
I've updated the comment above.
- Matrix size is 30K
- No other error messages beyond the one in slurm.
- It is not a memory issue, otherwise slurm would give me a memory error message (I have other fails like that).
- it seems related to the 7x7 blacs grid

P.S.: what I really miss with exact diagonalization is a progress bar telling me the status of the process.

**Comment by muralidhar-nalabothula** [comment]
I cannot reproduce the error with any of your listed configurations

I ran the calculations for Matrix size ```36864``` for the coupling case with the following list of configurations and All ran perfectly without the error your mentioning (I ran on two different clusters, one with intel cpus (8 year old) and other with AMD cpus (4 year old) ).
I used ```gfortran + openblas + scalapack```. Moreover I see on our cluster, they run way faster than yours ( are you using a decade old cpus?.)

81 cores (9x9 blacs grid) [OK]
64 cores (8x8 blacs grid) [OK]
56 cores (7x8 blacs grid) [OK]
51 cores (7x7 blacs grid) [OK]
50 cores (7x7 blacs grid) [OK]
48 cores (6x8 blacs grid) [OK]
42 cores (6x7 blacs grid) [OK]
36 cores (6x6 blacs grid) [OK]
26 cores (5x5 blacs grid) [OK]

I cannot converge more than 60 eigenvalues with slepc (using shell)

Here is the plot

for_davide

**Comment by sangallidavide** [comment]
Thanks Murali for digging into this. Anyway, for the 7x7 blacs grid, moving on 3 nodes the run completed succesfully. So, in the end, you might have been right and it was a memory issue (?)

This are the CPUs of my cluster: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Compilation: GNU Fortran (GCC) 10.2.1 20210130, Open MPI v4.1.1, OpenBLAS-0.3.21, scalapack internally compiled by yambo, FC_FLAGS="-O3 -g -mtune=native  -fopenmp", single 

Your simlations are indeed significantly faster, although the timing is rather flat. Are you considering the coupling case?

For slepc with coupling, I'm using an ad hoc version developed within a running project (Shao / Gruning algorithms).
We are interested in cases where the algorithm does not converge. Can you send me the inputs via email?

**Comment by sangallidavide** [comment]
I attach here a report on BSE solvers scaling, both weak and strong scaling, (still in progress). It shows, among other things, the very good performances of the new ydiago implementation
[BSE_solvers_scaling_V1.pdf](https://github.com/user-attachments/files/16839198/BSE_solvers_scaling_V1.pdf)

**Comment by sangallidavide** [comment]
Following discussion at the yambo meeting, I merge this pull request to a dedicated branch tech-ydiago inside the yambo repo. Further discussion will follow in a dedicated pull request from tech-ydiago to tech-master

**Pull request merged**
