### PR TITLE
Maintenance compilation

### PR DESCRIPTION
**Pull request by andreamarini**
In this branch I:

- reintroduced the simplified compilation that does not use project dependent targets that was reverted by @sangallidavide in one of the previous commits
- made the libraries to have names tagged with the specific executable: `_YPP_` and `_Y_` in order to solve the problems mentioned by @nicspalla and @andrea-ferretti in LUMI.

The implementation of a path to include `memory.h` and `parallel_memory.h` following @muralidhar-nalabothula  suggestions will be done soon.

### CODE REVIEW

**Comment by muralidhar-nalabothula** [comment]
Hello Andrea,

If you planning to make these changes, I would suggest the following format:
```#include <headers/common/memory.h>``` and pass the ```-I/path/to/yambo/include``` to the preprocessor. In this way, It will be very clear for developers where the header is located.

**Comment by andreamarini** [comment]
> Hello Andrea,
> 
> If you planning to make these changes, I would suggest the following format: `#include <headers/common/memory.h>` and pass the `-I/path/to/yambo/include` to the preprocessor. In this way, It will be very clear for developers where the header is located.

I totally agree. Thx for the suggestion! Very smart trick. Thanks!

**Comment by andrea-ferretti** [comment]
Hi All,

while I understand the use of _YPP_ and _Y_, which would be fine with me (assuming it solves the problem with LUMI, as it should, but needs testing), I do not get the point of further changing y_memory.h to something else...

* y_memory.h is already there
* we are now proposing a further renaming (including paths, ok), which is even more complicated to remember

what is the added value ? is it a style matter ?

If a style matter, I would probably stick to the existing option, just to minimize commits and changes (Occam's razor)

**Comment by sangallidavide** [comment]
I guess  the PR should be towards maintenance-master and not towards the master.

Besides this:

- I agree with what written below. Also because we are now working on top of maintenance-master. All the `memory.h` headers where changed inside tech-master ... trying to merge the two will be impossible.
> If a style matter, I would probably stick to the existing option, just to minimize commits and changes (Occam's razor)

- Introducing another rule, e.g. the `LAB` rule adding `_YPP_` or `_Y_`, in the already too complex compilation procedure is not a good idea

- I'm against re-introducing a structure where all folders are tagged to be compiled by all executables/project (e.g. `make yambo` activates the compilation of `real_time*` folders), and then a rule is added to check which set of folders should be compiled by each executable/project (e.g. `real_time*` folders are excluded from `make yambo`

**Comment by muralidhar-nalabothula** [comment]
Just to make it clear, I am not at all against renaming ```memory.h``` to ```y_memory.h```. I took it as an opportunity to share my personal experience and suggest something that improves readability and make it more beginner friendly. No issues if this does not make sense to core developers.

**Comment by andreamarini** [comment]
I personally like a lot the approach of @muralidhar-nalabothula  that explains perfectly also my point.

@sangallidavide. I respect your disagreement but I do not agree at all with all the points you raised. The compilation is now by far easier that before. And the ypp libraries were already tagged. I just added a tag to yambo libraries.

Side comment. The compilation procedure should be addressed in a maintenance branch and not in a tech branch. We are new to the new system so it will take time to use it properly.

Last but not least. Something coded can be improved. This is a collaborative project and not a way to code _against_ someone else.

So I reiterate this branch.

**Comment by sangallidavide** [comment]
We are discussing 2 different points here
(a) memory.h header
(b) other compilation related issues (including libmodules.a, but also going through the compilation scheme)

(a) memory.h
-----------------
The header was renamed in the tech-gpu branch (also) for enabling compilation of Lumi (we get money from MaX for that, this should not be ignored). This was done more than 1 year ago, before tech-master and maintenance-master existed, and finally entered in tech-master, since connected to gpu porting.

A point was raised on this renaming, and I also said it should be discussed. I also think the suggestion from Murali has some advantages. We just need to decide if changing again is worth the effort. However, what triggered the negative reaction is not option suggested from Murali by itself.

It was the unilateral decision to opt for a specific choice, before reaching an agreement in the yambo team, and, moreover, by doing so in a branch that (a.1) is not based on the latest changes, e.g. ensuring conflicts in all files if merged, and (a.2) together with other changes which have nothing to do with the present discussion 

(b) yambo compilation in general
-----------------
I discussed about the yambo compilation scheme with other developer, advanced user, inexperienced users, HPC experts, software engineers, developers from other groups. Everyone told me that it is one of the major barriers to the use of yambo and that, since when it was restructured, it get worse. I'm having issues myself in compiling yambo since quite some time. If we continue ignoring this point we will slowly loose more users and more developers.

Whatever the reasons for this situation, let's not insist on it, and try to improve it. We have support from software engigners within MaX. If we are not able to agree on something, let's ask them.

Conclusion
--------------
Before going straight for the solution proposed in this branch, we need to split the concerns and decide how to address each of them. This will ensure we opt for the best choice, and will minimize the burden for all developer in a subsequent merge.

**Comment by andreamarini** [comment]
So. We have a problem and 3 solutions.me (opt 1), DS (opt 2), NS (opt 3).

This is a paradigmatic situation. 

Each of these 3 persons spent time in coding, of course. Maybe to do the coding they had to leave out some other things they had to do.

DS suggests to wait and discuss carefully as we risk to loose users and developers. I could answer differently. Actually any developer could say something different.

This is clearly a vision difference. And, sorry to say, but we will never stop having these kind of clashes (this is not the first one) unless we decide an easy way to proceed. QE has P. Giannozzi, considered a coding master. Here I could play his role but whatever I propose is either ignored or criticized. So I cannot be him (even if I am the one with more experience).

I do think this simple example demonstrates the weakness of the Yambo coding method. And that's it.

I will continue the development in the devel repo in the meantime.

**Pull request closed without merging**
