### PR TITLE
Phys levels degeneracy

### PR DESCRIPTION
**Pull request by andreamarini**
As pointed in issue#122 yambo produces wrong results when the band levels defined in the input file do not respect the bare energy degeneracy.

In the case of Black-Phosphorus for some reason the effect is huge. But, in general, many cases are affected.

In this branch I have

- added a new levels degeneracy check in yambo.F  
image

- added a new routine (LEVELS_mirror) that embodied and generalizes the procedures previously contained in INIT_load

The branch is green (same errors of maintenance/master to be fixed) when launched without imposing the bands to respect the symmetry (robots of August 22-23) while the errors in the launches after are signature of the errors induced by wrong bands selection.

### CODE REVIEW

**Comment by sangallidavide** [comment]
Just a few questions/comments.

First a practical one.
- From what I understand, in systems with many degeneracies, this might impose a large number of bands. Is it possible to force a skip of the check from input?

Then some procedural ones.
- why is it called "phys"? I do not see any new physics. It seems more something like "maintenance" merge. Indeed, the branch is also in sync with "maintentance-master" (e.g. it contains the fixes which are there).

- The the robots did run on the "maintenance-master" branch of test-suite
https://media.yambo-code.eu/robots/GPL/phys-levels_degeneracy/mo.farah.3.php
I see few more errors compared to the "maintenance-master" branch
https://media.yambo-code.eu/robots/GPL/maintenance-master/mo.farah.4.php
Are these the errors mentioned above, due to not respecting the degeneracy? Does a connected test-suite branch exist, either fixing the reference files or imposing to skip the check from input?

- why the pull request towards "master"  and not towards "maintenance-master" ?

**Comment by andreamarini** [comment]
> Just a few questions/comments.
> 
> First a practical one.
> 
> * From what I understand, in systems with many degeneracies, this might impose a large number of bands. Is it possible to force a skip of the check from input?

In general the code adds  1-2 bands. Without results are wrong. So I would not put any option to get wrong results.

> 
> Then some procedural ones.
> 
> * why is it called "phys"? I do not see any new physics. It seems more something like "maintenance" merge. Indeed, the branch is also in sync with "maintentance-master" (e.g. it contains the fixes which are there).

It is phys as it motivated by a physical argument. Maintenance is just maintenance. No physics-specific.

> * The the robots did run on the "maintenance-master" branch of test-suite
>   https://media.yambo-code.eu/robots/GPL/phys-levels_degeneracy/mo.farah.3.php
>   I see few more errors compared to the "maintenance-master" branch
>   https://media.yambo-code.eu/robots/GPL/maintenance-master/mo.farah.4.php

Few. Enough to accept the pull request in line with what decided orally during the last meeting.

>   Are these the errors mentioned above, due to not respecting the degeneracy? Does a connected test-suite branch exist, either fixing the reference files or imposing to skip the check from input?

Yes. All errors in the ROBOTS starting today will be due to the bug.

I will then create a new test-suite branch with the corrected REFERENCES.

> * why the pull request towards "master"  and not towards "maintenance-master" ?

My mistake. I will fix it.

**Comment by sangallidavide** [comment]
These are databases created by manually interrupting a bse run.

They are meant to check that yambo is able to recover after a crash.

We could implement in the test-suite a kill signal after a given time.

**Comment by andreamarini** [comment]
Ok. For the moment I move the test to the BROKEN folder.

When there will be a test-suite procedure we will restore it.

**Comment by sangallidavide** [comment]
Instead of changing references and switching off some test, a simpler alternative is to add in the BSE inputs the option to skip the check on the degeneracies, so that old reference and databases files are ok.

**Pull request merged**
