### PR TITLE
Tech gpu

### PR DESCRIPTION
**Pull request by sangallidavide**
This branch contains developments on GPU porting mostly done by @andrea-ferretti 

It contain changes across many points in the code, and it should enter soon, in order to base subsequent developments on the updated version of the code. Otherwise many conflicts are likely to come out in new developments.

### CODE REVIEW

**Comment by andreamarini** [comment]
The branch does not compile on mo

https://media.yambo-code.eu/robots/GPL/tech-gpu/mo.farah.5.php

**Comment by sangallidavide** [comment]
> The branch does not compile on mo
> 
> https://media.yambo-code.eu/robots/GPL/tech-gpu/mo.farah.5.php

Fixed with commit [b7b43b3](https://github.com/yambo-code/yambo/pull/132/commits/b7b43b35db8d6790f1dfab213a83b00f55e9f62c)

**Comment by sangallidavide** [comment]
Addendum. The configure options for GPUs are changed with the present branch.

In order to compile with nvfortran and cuda fortran, these are the new options
`--enable-cuda-fortran --with-cuda-runtime=12.5 --with-cuda-cc=75`
which replace the one of the master
`--enable-cuda="cuda12.4,cc75"`

Moreover other options are available, such as
* openacc (which can be used in principle both with nvfortran and gfortran): 
`--enable-openacc --with-cuda-runtime=12.5 --with-cuda-cc=75`, to be complemented (gfortran case) with `--with-cuda-libs`
* openmp5  (which can be used in principle both with intel and gfortran)
`--enable-openmp5` to be complemented (?)  ` --with-cuda-runtime=12.5 --with-cuda-cc=75` and  with `--with-cuda-libs` / `--with-mklgpu-libs`

We need, indeed, to provide documentation for this. I'd suggest to upgrade this page (and linked pages):
https://www.yambo-code.eu/wiki/index.php/Installation

**Comment by andreamarini** [comment]
At the moment the robots cannot use branch-specific configurations. So this change would break the compilation.

The robots perl source has to be added to permit a specific branch to use ad-hoc compilations. Dunno how to do it.

Moreover the wiki must be changed ONLY after the release and not before.

We can create some temporary page, anyway.

**Comment by sangallidavide** [comment]
In the test-suite (perl source) the configuration options for a robot are already specified via the `CONFIG` scripts contained in the flow, right?

On my machine I have a dedicated flow for this branch, with its own configure script.
I guess in the control room the `MODULE` column defines the used flow. One could just define a new `module` such as `NV-24.1-GPU` or similar.

**Comment by andreamarini** [comment]
All the robots config files are in a separated repo. At the moment the test-suite is not able to switch between different robots repos. So if you change your config your robot will be able to run only the tech-gpu

**Comment by sangallidavide** [comment]
On my machine
```
./driver.pl -flow nvidia_cuda_master -branch tech-master -report
./driver.pl -flow nvidia_cuda_gpu    -branch tech-gpu    -report
```
First for tech-master, second for tech-gpu, same `master` repo for the robots ...

**Comment by andreamarini** [comment]
What I meant is that the automatic robots don't use flows by command line but a post-processed file obtained from the google table.

This means that we cannot point mo/eliud to tech-gpu

**Comment by sangallidavide** [comment]
As discussed not with Nicola, nvfortran+openacc is presently not working.

It works with the following patch (which restores previous implementation, slower than CUDAF)
```
diff --git a/include/headers/common/dev_defs.h b/include/headers/common/dev_defs.h
index c8e6f95d59..a8319f6415 100644
--- a/include/headers/common/dev_defs.h
+++ b/include/headers/common/dev_defs.h
@@ -45,8 +45,10 @@
 
 #if defined _OPENACC
 #  define DEV_ACC $acc
+#  define DEV_ACC_DEBUG $acc
 #else
 #  define DEV_ACC !!!!
+#  define DEV_ACC_DEBUG !!!!
 #endif
 
 #if defined _CUDAF
```

**Comment by andreamarini** [comment]
Hi. I have started analyzing the tech-master.

I start with two questions:

- why did you rename src/modules?
- why did you rename memory.h

I will post here more questions as soon as I analyze the source.

**Comment by sangallidavide** [comment]
The reason is that `memory.h` and `libmodules.a` are very general and present in the os.
So we wanted to be sure to avoid linking the wrong file. 
On my machine for example it exist
```/usr/include/memory.h```

- `memory.h` --> `y_memory.h` renaming was done. But I think it never gave problems. 
- `libmodules.a` --> `libYmodules.a` I think was done because it gave some problems at a certain point.
@nicspalla might have more info

Anyway, I agree that we should carefully checked this before doing the changes.

As a side remark. It is a bad practice to have all modules in a folder, it would be better to have the modulse spread across the different folders, each one associated with the connected `libxxx.a`

**Pull request merged**
